name: Verify Build
run-name: ${{ github.actor }} pushed new commits.
on: [push]
jobs:
  VerifyBuild:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
      - name: Run Tests
        run: |
          cd ${{ github.workspace }}
          go test -v ./...