name: Verify Build
run-name: ${{ github.actor }} pushed new commits.
on: [push]
jobs:
  VerifyBuild:
    name: Run Tests
    runs-on: ubuntu-latest
    env:
#      GOPATH: "$HOME/go"
#      PATH: "$PATH:%GOPATH/bin"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20
#      - name: Setup Git
#        run: git config --global url."https://${{https secrets.GITHUB_TOKEN }}:@github.com/".insteadOf "https://github.com"
      - name: Install Dependencies
        run: |
          go mod download
      - name: Code Check
        run: |
          go vet -json ./... >vet_results.json
      - name: Build
        run: |
          go build ./...
      - name: Run Tests
        run: |
          go test -json ./... 2>&1 >test_results.json
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          path: "*_results.json"
        if: always()